# Generated by Django 4.1.1 on 2022-12-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addProductModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProduct', models.CharField(max_length=50)),
                ('keterangan', models.TextField(max_length=200)),
                ('owner', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='/static/img/')),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
