# Generated by Django 4.1.1 on 2022-12-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_addproductmodels_gambar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addProductModels',
            new_name='Product',
        ),
    ]
