# Generated by Django 4.1.1 on 2022-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rename_addproductmodels_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, default='static/img/kamar.jpg', null=True, upload_to=''),
        ),
    ]
