# Generated by Django 4.1.1 on 2022-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_alter_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
